# Adapted from https://github.com/commercialhaskell/stack
language: c
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  include:
  #   # ghc 8.0.2
  # - env: STACK='stack --resolver=lts-8.24' CACHE_NAME=8.0.2
  #   addons: {apt: {packages: [libgmp-dev]}}

  #   # ghc 8.2.2
  # - env: STACK='stack --resolver=lts-11.5' CACHE_NAME=8.2.2
  #   addons: {apt: {packages: [libgmp-dev]}}

    # ghc 8.4.4
  - env: STACK_YAML=stack-8.4.4.yaml CACHE_NAME=8.4.4
    addons: {apt: {packages: [libgmp-dev]}}

    # ghc 8.6.4
  - env: STACK_YAML=stack-8.6.4.yaml CACHE_NAME=8.6.4
    addons: {apt: {packages: [libgmp-dev]}}

    # nightly
  - env: STACK='stack --resolver=nightly' CACHE_NAME=nightly
    addons: {apt: {packages: [libgmp-dev]}}

    # Use the resolver in stack.yaml
  - env: STACK_YAML=stack.yaml CACHE_NAME=stack-linux
    addons: {apt: {packages: [libgmp-dev]}}

  - env: STACK_YAML=stack.yaml CACHE_NAME=stack-osx
    os: osx
    addons: {apt: {packages: [libgmp-dev]}}


install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

script:
 - echo "$($STACK ghc -- --version) [$($STACK ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   stack --no-terminal build --ghc-options="$GHC_OPTIONS"
   stack test --ghc-options="$GHC_OPTIONS"
   set +ex

after_success:
 - |
   # Build and ship binary
   ./.travis/attach-binary.sh

